// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBauw66GS9BdFayO82AEcGUkD4cBU85JJo',
    appId: '1:292776541175:web:b47c7cb0f01b27e37f8cf2',
    messagingSenderId: '292776541175',
    projectId: 'aina-task-manager',
    authDomain: 'aina-task-manager.firebaseapp.com',
    storageBucket: 'aina-task-manager.firebasestorage.app',
    measurementId: 'G-GM59SM2BRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcMV5WY3xn7i8GASqwQQEB7eYuI2AtwR8',
    appId: '1:292776541175:android:dcc5ef13cb30a3ed7f8cf2',
    messagingSenderId: '292776541175',
    projectId: 'aina-task-manager',
    storageBucket: 'aina-task-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBswXMiouS7BO4niMUH-aZ-6wkj8Fz9xt4',
    appId: '1:292776541175:ios:dae049e4feded5f97f8cf2',
    messagingSenderId: '292776541175',
    projectId: 'aina-task-manager',
    storageBucket: 'aina-task-manager.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBswXMiouS7BO4niMUH-aZ-6wkj8Fz9xt4',
    appId: '1:292776541175:ios:dae049e4feded5f97f8cf2',
    messagingSenderId: '292776541175',
    projectId: 'aina-task-manager',
    storageBucket: 'aina-task-manager.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBauw66GS9BdFayO82AEcGUkD4cBU85JJo',
    appId: '1:292776541175:web:3c2068588dde24da7f8cf2',
    messagingSenderId: '292776541175',
    projectId: 'aina-task-manager',
    authDomain: 'aina-task-manager.firebaseapp.com',
    storageBucket: 'aina-task-manager.firebasestorage.app',
    measurementId: 'G-C11ZV7GKJG',
  );
}
